name: hierarchical
description: Hierarchical List Components using AngularDart.
version: 0.0.1
dependencies:
  angular: any
  browser: any
dev_dependencies:
  guinness: any
  mock: any
  unittest: any
transformers:
- angular
